services:
  sqlserver-prod:
    image: 'mcr.microsoft.com/mssql/server:latest'
    container_name: 'sqlserver-prod'
    profiles: [prod]
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_PID=express'
      - 'MSSQL_SA_PASSWORD=verYs3cret'
    ports:
      - '1433'
    platform: 'linux/amd64'

  sqlserver-test:
    image: 'mcr.microsoft.com/mssql/server:latest'
    container_name: 'sqlserver-test'
    profiles: [test]
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_PID=express'
      - 'MSSQL_SA_PASSWORD=verYs3cret'
    ports:
      - '1433'
    platform: 'linux/amd64'

  sqlserver-dev:
    image: 'mcr.microsoft.com/mssql/server:latest'
    container_name: 'sqlserver-dev'
    profiles: [dev]
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_PID=express'
      - 'MSSQL_SA_PASSWORD=verYs3cret'
    ports:
      - '1433'
    platform: 'linux/amd64'

  sqlserver-it:
    image: 'mcr.microsoft.com/mssql/server:latest'
    container_name: 'sqlserver-it'
    profiles: [it]
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_PID=express'
      - 'MSSQL_SA_PASSWORD=verYs3cret'
    ports:
      - '1433'
    platform: 'linux/amd64'